name: Vtoroe_dyhanie

# Workflow будет срабатывать на команду push в ветку develop
on:
  push:
    branches: [ develop ]

# После срабатывания "on" выполнятся следующие действия:
jobs:
  tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu 
    runs-on: ubuntu-latest

    steps:
    # Запуск actions checkout — готового скрипта 
    # для клонирования репозитория
    - uses: actions/checkout@v2
    - name: Set up Python
      # Запуск actions setup-python — готового скрипта 
      # для развёртывания окружения Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort mypy
        pip install -r requirements.txt 

    - name: Test with flake8 and mypy
      run: |
        cd src/
        python -m flake8
